### ISSUE TITLE
Big environment variables cause cinnamon-session segfault

### ISSUE THREAD

**Issue by nbyouri** [linuxmint/cinnamon-session#118]
```
 * Version 3.8.1
 * Distribution - NetBSD 7.1.2
 * i915drmkms
 * amd64
 ```

**Issue**

My LS_COLORS environment variable is 6000+ chars long and g_regex_match causes a segfault in 
cinnamon-session/csm-util.c line 591.

**Steps to reproduce**

I've extracted the code to reproduce the failure:

```c
#include <stdio.h>
#include <string.h>
#include <err.h>

#include  <glib.h>

int main(void) {
        GRegex  *regex;

        regex = g_regex_new("^([[:blank:]]|[^[:cntrl:]])*$", G_REGEX_OPTIMIZE,
                        0, NULL);

        if (regex == NULL)
                err(EXIT_FAILURE, "failed g_regex_new value_regex");

        const char *value = g_getenv("LS_COLORS");

        if (g_utf8_validate(value, -1, NULL) == 0)
                err(EXIT_FAILURE, "failed to validate utf8");

        printf("validated.\n");
        printf("%s\n\n", value);

        if (g_regex_match(regex, value, 0, NULL))
                err(EXIT_FAILURE, "failed to regex_match");

        g_regex_unref(regex);


        return EXIT_SUCCESS;
}
```

Using an LS_COLORS variable available [here](https://paste.xinu.at/LS9)

Of course by removing LS_COLORS from the environment cinnamon-session does not crash.

**Comment by clefebvre** [comment]
Hi @nbyouri, thanks for this report and for isolating the issue with this little program.

I'm not sure what we can do on our side.. this probably should be reported upstream to Glib.
