### ISSUE TITLE
Cinnamon session shouldn’t upload XDG_SESSION_ID to systemd —user

### ISSUE THREAD

**Issue by ItzSwirlz** [linuxmint/cinnamon-session#140]
See: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=986099

**Comment by leigh123linux** [comment]
Looks like gnome fixed it with this https://github.com/GNOME/gnome-session/commit/646b9bc0584d02033ab9600c39b77d6f99bfc4a6
