### ISSUE TITLE
Green screen after login when new kernel applied

### ISSUE THREAD

**Issue by dan63043** [linuxmint/cinnamon-session#156]
```
 * cinnamon-session version 5.8.1 (but system info shows 5.8.4)
 * Distribution - Mint 21.2
 * Card: [AMD/ATI] Wani [Radeon R5/R6/R7 Graphics] (rev c8)
   Driver: amdgpu
 * 64 bit
 ```

**Issue**
After login, the screen goes green and gets horizontal lines dancing across it.

**Steps to reproduce**
Simply login to cinnamon

**Expected behaviour**
Should be the desktop

**Other information**
I can login from another box to collect any diagnostics that you need.

**Comment by leigh123linux** [comment]
This isn't a cinnamon issue, it's either a kernel or mesa issue.
File it at https://github.com/linuxmint/linuxmint/issues
