### ISSUE TITLE
cinnamon-session[844]: GLib-CRITICAL: t+1.96972s: g_child_watch_add_full: assertion 'pid > 0' failed

### ISSUE THREAD

**Issue by istenburg** [linuxmint/cinnamon-session#157]
### Distribution

Arch Linux

### Package version

Cinnamon 5.8.4

### Graphics hardware in use

Nvidia RTX 2070 Super

### Frequency

Always

### Bug description

After updating to Cinnamon version 5.8.4 the error occurred
`Nov 21 06:23:30 I-NET cinnamon-session[844]: GLib-CRITICAL: t+1.96972s: g_child_watch_add_full: assertion 'pid > 0' failed`

### Steps to reproduce

reboot

### Expected behavior

Unfortunately, I don't know how to fix the error...

**Comment by leigh123linux** [comment]
Fixed
