### ISSUE TITLE
cinnamon-session does not shutdown PC

### ISSUE THREAD

**Issue by archiebug** [linuxmint/cinnamon-session#173]
```
 * cinnamon-session 6.2.0
 * Arch
 * AMD 6800XT, latest Mesa
 * 64 bit
 ```

**Issue**
When using shutdown command, session just quits and goes to lightdm

**Steps to reproduce**
Upgrade to latest cinnamon session. 
(use PC) open apps (steam, brave, etc..)
menu -> power button -> shutdown

shutdown command closes down apps then dumps to lightdm

**Expected behaviour**
cinnamon-session shuts down PC

**Other information**
downgrading cinnamon packages to previous version restores functionality

some discussion on the arch forums: https://bbs.archlinux.org/viewtopic.php?id=296820

log files:
```
Jun 16 09:12:46 archie python[4915]: Attribute Qt::AA_ShareOpenGLContexts must be set before QCoreApplication is created.
Jun 16 09:14:54 archie cinnamon-session-binary[3955]: WARNING: t+188.69946s: Client '/org/gnome/SessionManager/Client26' failed to reply before timeout
Jun 16 09:15:00 archie cinnamon-session-binary[3955]: WARNING: t+194.81883s: Playing logout sound '/usr/share/mint-artwork/sounds/logout.ogg'
Jun 16 09:15:01 archie at-spi2-registr[4094]: Failed to send session response Timeout was reached
Jun 16 09:15:01 archie cinnamon-session-binary[3955]: WARNING: t+196.21491s: Finished playing logout sound
Jun 16 09:15:01 archie cinnamon-session-binary[3955]: WARNING: t+196.21496s: Resuming logout sequence...
Jun 16 09:15:02 archie dbus-broker[4084]: Dispatched 754 messages @ 2(±4)μs / message.
Jun 16 09:15:02 archie wireplumber[3938]: m-dbus-connection: <WpDBusConnection:0x63e151fcf0d0> DBus connection closed: Underlying GIOStream returned 0 bytes on an async read
Jun 16 09:15:02 archie gvfsd[4056]: A connection to the bus can't be made
Jun 16 09:15:02 archie cinnamon-session-binary[3955]: WARNING: t+196.83747s: Requesting system shutdown...
Jun 16 09:15:02 archie cinnamon-session-binary[3955]: WARNING: t+196.83751s: Attempting to shutdown using systemd...
Jun 16 09:15:02 archie systemd[3928]: Stopping D-Bus User Message Bus...
Jun 16 09:15:02 archie cinnamon-session-binary[3955]: GLib-CRITICAL: t+196.83788s: g_hash_table_foreach_remove_or_steal: assertion 'version == hash_table->version' failed
Jun 16 09:15:02 archie cinnamon-session-binary[3955]: CRITICAL: t+196.83822s: Unable to start session: Lost name on bus: org.gnome.SessionManager
Jun 16 09:15:02 archie systemd[1]: run-user-1000-gvfs.mount: Deactivated successfully.
Jun 16 09:15:02 archie gvfsd[4292]: A connection to the bus can't be made
Jun 16 09:15:02 archie cinnamon-session-binary[3955]: WARNING: t+196.83828s: Requesting system shutdown...
Jun 16 09:15:02 archie wireplumber[3938]: m-dbus-connection: <WpDBusConnection:0x63e151fcf0d0> Trying to reconnect after core sync
Jun 16 09:15:02 archie cinnamon-session-binary[3955]: WARNING: t+196.83830s: Attempting to shutdown using systemd...
Jun 16 09:15:02 archie dbus-broker[3949]: Dispatched 3448 messages @ 3(±5)μs / message.
Jun 16 09:15:02 archie systemd[1]: run-user-1000-doc.mount: Deactivated successfully.
Jun 16 09:15:02 archie systemd[3928]: gvfs-daemon.service: Failed to kill control group /user.slice/user-1000.slice/user@1000.service/session.slice/gvfs-daemon.service, ignoring: Invalid argument
Jun 16 09:15:02 archie systemd[3928]: gvfs-daemon.service: Failed to kill control group /user.slice/user-1000.slice/user@1000.service/session.slice/gvfs-daemon.service, ignoring: Invalid argument
```

**Comment by leigh123linux** [comment]
Try https://github.com/linuxmint/cinnamon-session/pull/172

**Comment by Zerophase** [comment]
I have the same issue. I configured auto login, and my shutdown seems to behave slightly differently. Might be a workaround.

 When I shutdown I go to a black screen with a black cursor. If I hold the power button down I exit out of lightdm to the tty, and the shutdown process continues.

**Comment by olebowle** [comment]
#172 fixes the issue on my end.

**Comment by emperor06** [comment]
Thanks for the quick fix @leigh123linux 

On Arch, you can patch your cinnamon-session until it's fixed in the repo:

```
cd /tmp/
pkgctl repo clone --protocol=https cinnamon-session
cd cinnamon-session
sed "/build()/ased '/maybe_restart_user_bus (manager);/d' -i \${pkgname}-\${pkgver}/cinnamon-session/csm-manager.c" -i PKGBUILD
makepkg -cirs
```
Basically, pull the official PKGBUILD, insert a sed command to drop the call to maybe_restart_user_bus(), install the build dependencies, build, install, remove the dependencies.

**Comment by archiebug** [comment]
> Thanks for the quick fix @leigh123linux
> 
> On Arch, you can patch your cinnamon-session until it's fixed in the repo:
> 
> ```
> cd /tmp/
> pkgctl repo clone --protocol=https cinnamon-session
> cd cinnamon-session
> sed "/build()/ased '/maybe_restart_user_bus (manager);/d' -i \${pkgname}-\${pkgver}/cinnamon-session/csm-manager.c" -i PKGBUILD
> makepkg -cirs
> ```
> 
> Basically, pull the official PKGBUILD, insert a sed command to drop the call to maybe_restart_user_bus(), install the build dependencies, build, install, remove the dependencies.

This worked perfectly.  I also learned something new today.  So, thank you for that!

**Comment by Jusix** [comment]
Is only Arch affected by this issue or how can it be that Linux Mint 22 beta was released today without a fix for this?

**Comment by emperor06** [comment]
Hard to tell. The update arrived today on Manjaro stable and I didn't have any issue, while both Arch and Cachy couldn't reboot/shutdown. There are probably other factors. I guess it's well tested on Mint, though.

**Comment by JosephMcc** [comment]
> Is only Arch affected by this issue or how can it be that Linux Mint 22 beta was released today without a fix for this?

As far as I can tell, it doesn't occur on Mint. At least I've never run into it.

**Comment by leigh123linux** [comment]
> Is only Arch affected by this issue or how can it be that Linux Mint 22 beta was released today without a fix for this?

fedora f40 and rawhide were affected, openmandriva also use my PR

**Comment by ObsidianRazor** [comment]
> Thanks for the quick fix @leigh123linux
> 
> On Arch, you can patch your cinnamon-session until it's fixed in the repo:
> 
> ```
> cd /tmp/
> pkgctl repo clone --protocol=https cinnamon-session
> cd cinnamon-session
> sed "/build()/ased '/maybe_restart_user_bus (manager);/d' -i \${pkgname}-\${pkgver}/cinnamon-session/csm-manager.c" -i PKGBUILD
> makepkg -cirs
> ```
> 
> Basically, pull the official PKGBUILD, insert a sed command to drop the call to maybe_restart_user_bus(), install the build dependencies, build, install, remove the dependencies.

This worked for me too, thanks!

**Comment by echuber2** [comment]
Before patching, is it a viable workaround to log out of Cinnamon and shut down or restart from the login screen instead?

**Comment by archiebug** [comment]
Yes- logging out of the session and then shutdown/restart from login works.

-------- Original Message --------

**Comment by Zerophase** [comment]
> Before patching, is it a viable workaround to log out of Cinnamon and shut down or restart from the login screen instead?

Just hitting the power button works too. After you get the black screen with a cursor, briefly pressing the power button should cause the rest of your shutdown process to continue.
