### ISSUE TITLE
nm-applet no longer auto starts requiring manual start

### ISSUE THREAD

**Issue by Shawn-Hub** [linuxmint/cinnamon-session#178]
```
 * cinnamon-session version (cinnamon-session --version)
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
 * Graphics hardware *and* driver used
 * 32 or 64 bit
 ```

**Issue**

nm-applet no longer auto starts. cannot add it to cinnamon startup applications. network status notifications are gone with  cinnamon-session 6.4.0-1. have to downgrade to cinnamon-session 6.2.1-1 to get back the way it was.

**Steps to reproduce**
running cinnamon-session 6.4.0-1 while loging in to cinnamon desktop

**Expected behaviour**

nm-applet starts on cinnamon login and there are notifications of network status when connecting or disconnecting network

**Other information**

**Comment by leigh123linux** [comment]
It's done by design, see https://github.com/linuxmint/cinnamon-session/commit/12685216ff88def58c2e03e5c0aa686567c1ffcc
