### ISSUE TITLE
cinnamon-session/cinnamon2d fails to start without hardware acceleration in cloud/remote environments (Forwarded-X/XRDP/VNC/NX/X2GO/Chromoting) 

### ISSUE THREAD

**Issue by hermlnx** [linuxmint/cinnamon-session#56]
Please back-port the fix from gnome-session into cinnamon-session in order to allow access to cinnamon in cloud or over remote sessions.

Details on repeating the problem using XRDP is detailed in Mint forum "viewtopic.php?f=208&t=118495" 

The patch is located here: https://bug731173.bugzilla-attachments.gnome.org/attachment.cgi?id=290278 

The long standing Gnome-session bug gnome-bugs #731173 was recently back-ported into Ubuntu 14.04, see  https://bugs.launchpad.net/ubuntu/+source/gnome-session/+bug/1251281

**Comment by clefebvre** [comment]
That fixes gnome-session load gnome-session-fallback.. it's not relevant to cinnamon.

The issue with Cinnamon is that it crashes in RDP... and that has nothing to do with cinnamon-session. I'd love to fix it, but that isn't the way.
