### ISSUE TITLE
HiDPI screen support

### ISSUE THREAD

**Issue by fatalcoder** [linuxmint/cinnamon-session#83]
Having issues with size of elements on login screen.
I have DELL XPS 13 with QHD (3200x1800) and set "Auto" in UI scale settings.
After logging in everything works fine.
Is there any solution to set this scaling factor in session component too ?

![wp_20161127_11_20_29_pro](https://cloud.githubusercontent.com/assets/3192656/20647457/09710328-b495-11e6-96e9-ae0683b70ac9.jpg)

**Comment by leigh123linux** [comment]
You will need to file the issue against whatever display manager your using (mdm, lightdm or gdm).

**Comment by leigh123linux** [comment]
For lightdm you can increase font size

https://solus-project.com/forums/viewtopic.php?f=11&t=2367

**Comment by leigh123linux** [comment]
I have a dirty hack for lightdm-gtk-greeter

https://dl.dropboxusercontent.com/u/6907158/hidpi.patch

**Comment by fatalcoder** [comment]
Thanks for help
