### ISSUE TITLE
Feature request: could we have a 'log off' item in the power-off-button-generated shutdown menu, please? 

### ISSUE THREAD

**Issue by CottonEaster** [linuxmint/cinnamon-session#92]
The Mint Menu offers an icon for logging off. So does the users applet. However, when I press the shutdown button on my laptop, the resulting window does not offer logoff. Also, I'd like it not to offer hibernation, whilst retaining the option to hibernate in other ways. One-stop solution: a system setting GUI that allowed one to determine what appears in this menu.

PS: This request was originally filed - and gathered some support - [here, on the Cinnamon bugtracker](https://github.com/linuxmint/Cinnamon/issues/6530#issuecomment-307561063).

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
