### ISSUE TITLE
Cinnamon crashing at shutdown

### ISSUE THREAD

**Issue by Likutar** [linuxmint/cinnamon-session#96]
Happens more often then not, although I couldn't find the exact cause. stopping the shutdown processes and running journalctl gave me the following entry:

[cinnamon-journalctl-dump.txt](https://github.com/linuxmint/cinnamon-session/files/1116008/cinnamon-journalctl-dump.txt)

I also occasionally have a message that at-spi-bus-launcher isn't shutting down, although I believe it might be unrelated

I'm running Antergos, however when using Arch Linux I had the same problem albeit without the at-spi-bus-launcher issue. I haven't tested other DE to confirm if the bus-launcher issue is a unrelated problem or not.

Should necessary I can provide more logs.

Additional info: 
I use a pci-passthrough for gaming however the error manifested without ever starting the vm.
My sessions usually compromise of Steam, Discord, Vivaldi, Clementine, Synergy and Virt-Manager
Not launching any of those didn't make a difference

**Comment by leigh123linux** [comment]
Supply a useful backtrace with debug symbols otherwise it will be close as insufficient info.

**Comment by leigh123linux** [comment]
The crash is occurring in cinnamon 
```
jun 30 13:53:56 Matheus-Desktop kernel: cinnamon[1053]: segfault at 18 ip 00007f6be53bf820 sp 00007ffd50005f70 error 4 in libgtk-3.so.0.2200.16[7f6be4ffd000+6eb000]
```

Don't bother to open another issue unless you provide a proper backtrace!!
